### ISSUE TITLE
Include deviance function

### ISSUE THREAD

**Issue by bc2zb** [willtownes/glmpca#1]
Hello, very happy that you've pulled out glmpca to run as a separate package. Is there a plan to include the deviance functions as well in this package?

**Comment by willtownes** [comment]
Hi thanks for your interest. We are planning to put all the other functionality into a separate bioconductor package that uses glmpca as a dependency. That way folks who are not in genomics could still use glmpca for dimension reduction on other data types, and we can support things like SingleCellExperiment objects in the bioconductor package. I will leave this issue open as a reminder to myself to notify you when the bioc package is available.

**Comment by willtownes** [comment]
The new bioconductor package [scry](https://www.bioconductor.org/packages/release/bioc/html/scry.html) implements both the deviance and null residuals functions. It is still [under active development](https://github.com/kstreet13/scry) and we hope to enable computation of these functions on massive datasets that can't fit in memory in the near future.
