### ISSUE TITLE
Computation Speed

### ISSUE THREAD

**Issue by SONGDONGYUAN1994** [willtownes/glmpca#16]
My data is 150 genes * 20,000 cells. Some genes are lowly expressed (e.g., expressed in < 50 cells), but no all zero genes. Now it takes me 12 hours to get 400 cycles and still not converge. Do you have any suggestions for this?

Thanks for Will's reply in email, and I would like to paste it here for future reference:

Here are some questions/ suggestions I have for you:

* are your counts from a UMI protocol?
Yes, it is UMI data.

* how many latent dimensions are you trying to obtain (the L parameter)?
24

* what likelihood are you using- Poisson or negative binomial?
I use NB; actually, do we really have Poisson case? Even for bulk-RNA sea data, people tend to believe they are NB.

* what is the maximum count in the entire data matrix?
It is about 10 thousand.

* try setting verbose=TRUE in the optimization and see if the deviance is steadily decreasing (it should). If it spikes really high you may need to increase the "penalty" parameter to improve the regularization.
The deviance is decreasing, but increasing the penalty does help!

* why only 150 genes? Usually people keep about 1,000-2,000 genes using some kind of feature selection. Our suggestion is to rank the genes by deviance, you can do it with the new scry package we just released (https://bioconductor.org/packages/release/bioc/html/scry.html ). 
Oh, we have a special case here: we have another FISH data, and we need to use the shared genes (150 genes) between FISH and scRNA-seq. We have no choice.

* If you want a faster but less accurate approach than GLM-PCA, scry also supports computing the deviance residuals which is a closed form operation. You can then pass them to standard PCA and it should approximate GLM-PCA. Some of our collaborators are currently working to make this apply to sparse matrices and delayedArray (disk-based, eg HDF5) data, but currently only works with a dense matrix representation.
Thanks! I would like to try that!

* I am currently working to improve the speed and memory efficiency of the GLM-PCA optimizer so that it can also handle sparse Matrix and disk-based data. It might be a few weeks though before it's ready.
Looking forward to it!

* Are there any cells that have zero across all genes?
No, I make sure that there is no "0" genes or "0" cells.

Thanks again for Will's help!

**Comment by willtownes** [comment]
this should now be addressed by version 0.2.0 which can be installed from github
