### ISSUE TITLE
an error of GLMPCA

### ISSUE THREAD

**Issue by 1156054203** [willtownes/glmpca#17]
I meet an error when usring 'scry' in my test data that format is a matrix. Running 'GLMPCA'command,it will raise an error when the parameter L be set to 5. But, it works well if I convert the data logarithmically. Even though when I'm using test data 'sce_full_Zhengmix4eq()',it also work well. I can't solve the problem,and hope to get your help.The R version I used was 3.6.1.

**Comment by willtownes** [comment]
please try increasing the penalty parameter. For example, try penalty=10 (the default is penalty=1). The penalty is similar to the idea of ridge regression, it shrinks the estimated parameters closer to zero but stabilizes the numerical computation.

**Comment by willtownes** [comment]
please try also installing version 0.2.0 from github, it is faster and can scale to larger "L" values
