### ISSUE TITLE
P-values for covariate coefficients?

### ISSUE THREAD

**Issue by leon-seranova** [willtownes/glmpca#34]
Any recommendations for estimating significance of the `coefX` and `coefZ` coefficients?

**Comment by willtownes** [comment]
Great question. I haven't thought about this much, but I recommend checking out Jeff Miller's [generalized bilinear models paper](https://arxiv.org/abs/2010.04896) and the [GBM github repository](https://github.com/jwmi/BilinearModels.jl). His approach does a much better job with uncertainty quantification.

**Comment by leon-seranova** [comment]
Thanks for the reference. My dataset has both sample and gene covariates and GBMs seem like a great fit!
