### ISSUE TITLE
Error if `L=1`

### ISSUE THREAD

**Issue by const-ae** [willtownes/glmpca#5]
Hi Will,

I was just playing around a bit with your package, which looks quite useful, when I noticed, that the `glmpca()` method fails when I try to get only the first PCA dimension (`L = 1`).

``` r
library(glmpca)
counts <- matrix(rpois(n=100 * 5, lambda = 5), ncol = 5, nrow=100)
# Works fine
res <- glmpca(counts, L = 2)
# Fails
res <- glmpca(counts, L = 1)
#> Error in 1:L: argument of length 0
```

<sup>Created on 2019-10-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I believe the error might be because you are missing a `drop=FALSE` [here](https://github.com/willtownes/glmpca/blob/master/R/glmpca.R#L44).

Best Regards,
Constantin

**Comment by willtownes** [comment]
thanks for pointing that out, it should be working now.

**Comment by const-ae** [comment]
Great, thanks for the quick fix :)
