### ISSUE TITLE
automatic penalty increase with warning

### ISSUE THREAD

**Issue by SamueleSoraggi** [willtownes/glmpca#6]
Dear Will,

I read with a lot of interest your glm-pca article. It is very well explained and I am sure it sheds a lot of light on the math behind SC data - and it is just what is needed in this field!

I would like to ask you about two things:
1) if I want to introduce a batch covariate in the analysis, I should convert it in integer numbers, is it right? For example, an array of 0s and 1s if I have two batches.
2) let's say I put a bunch of features for each cell and for each gene in the glm-pca function. When I see the results, I can study the glm model coefficients for each feature. Those coefficients can be used to get an impression of which features are more relevant than others, and one could select only the most relevant one and run again the glm-pca, or use this information to consider covariates in further analysis (i.e. diffrential gene expression). Am I right?

And thanks for a ready to use implementation - I am testing it on some datasets I am working on - and I can definitely see an improvement over the sloppy log(cpm+1) approach - but also on some cases in which I used scTransform from Seurat

**Comment by willtownes** [comment]
Thanks for your kind remarks! 

1. Exactly right you should create a design matrix using something like `model.matrix` as glmpca does not allow factors in X. Keep in mind glmpca always includes an intercept term so if you have indicator variables for batch you will want to have one less indicator than the number of batches, which should be the case if you use `model.matrix`. Also, the X matrix can also have numeric covariates not just binary ones.

2. I'm a little confused here. When you say "cell features" I assume you mean "cell covariates" (X) and gene features are the covariates matrix we call Z. For the sake of argument let's ignore Z and focus on X. If you include something like a biological condition indicator in X (say drug treated vs normal), the glmpca will output a matrix called `coefX` which contains a gene-specific coefficient for each column of X. The first column of coefX is the intercept which is always included so ncol(coefX)=ncol(X)+1. These coefficients could indeed be interpreted as measuring differential expression between the conditions. Furthermore, if you included several latent dimensions (L>0) those would absorb "excess" variation in a manner similar to RUVseq or SVA. However, we have not tested this approach and I would not be surprised if dedicated differential expression tools like DESeq2 outperform in this context. If you do compare them let us know as it's an interesting idea.

I'm not sure I understand why you would want to iteratively run glmpca and subselect features based on the results of the differential expression comparison? It seems like it would be simpler and faster to just fit a separate GLM for each feature with the same design matrix and then rank the features based on having the smallest deviance.

**Comment by SamueleSoraggi** [comment]
Hi, thanks for your explanations.

I think I had the wrong idea in mind when I wrote the second question, I had skimmed the last part of the paper and I had to read more carefully. Now I understand I said something without too much sense, but your explanation helped a lot (and also reading better the paper)!

I have been trying out the GLMPCA on a dataset where I already used PCA + UMAP. So far the visualization I get seems still better when I base UMAP on the traditional PCA. I guess I will have to try to use additional latent dimensions.

I will also have a look at the approach for differential expression analysis - it is indeed something that again interests me quite a lot. I might update you on further results then :)

Cheers.

**Comment by willtownes** [comment]
OK I'm glad we cleared up the confusion somewhat. I definitely need to improve the documentation. Regarding your dataset where PCA does better- is it with UMIs or read counts? What kind of feature selection are you doing? We have sometimes observed that glmpca does not do very well with HVG as feature selection- it usually works best when you filter the genes based on deviance instead.

**Comment by SamueleSoraggi** [comment]
Hi, it is UMI data from 10X. I also have to say that is really sparse and affected by noise, since it comes from nuclei and not whole cell. I have tried it with a limited number of genes (the same selected by the normalization scTransform I usually apply to data). I tried with incrementing the number of genes used, and the results got better. Now I will see how it goes with the whole gene set.

A last thing, this time implementation-related: as probably many other users, I run my analysis in small pipelined chunks of commands on a server. This means that if there is an error, all the sequence of commands I am running will stop. It happens often that glmpca stops due to the penalty not being high enough - do you think you can change that error with a warning and an automatic increase of the penalty term? So that the software actually continues working instead of stopping. I am talking about the python implementation, but just realized I have been posting on the R implementation page!

**Comment by willtownes** [comment]
automatic penalty tuning is now available
