### ISSUE TITLE
divergence even after increased penalties 

### ISSUE THREAD

**Issue by ttriche** [willtownes/glmpca#7]
```
R> library(SingleCellExperiment)
R> (sce <- readRDS("sc/sce.rds"))
class: SingleCellExperiment 
dim: 31053 40051 
metadata(8): Samples Samples ... Samples Samples
assays(2): counts logcounts
rownames(31053): ENSMUSG00000051951 ENSMUSG00000089699 ...
  ENSMUSG00000096730 ENSMUSG00000095742
rowData names(3): ID Symbol Type
colnames(40051): AAACCTGAGAAACCAT-1 AAACCTGAGACTAGGC-1 ...
  TTTGTCACATCCTTGC-1 TTTGTCATCGGCGCTA-1
colData names(7): Sample Barcode ... cd45 genotype
```
So the dataset isn't _too_ ridiculous

```
R> library(glmpca) 
```
From CRAN

```
R> res <- glmpca(counts(sce), L=10, penalty=100) 
Error in glmpca_init(Y, fam, sz, nb_theta) : 
  Some rows were all zero, please remove them.
``` 

OK, we can fix this pretty easily:
```
R> nonzero <- which(rowSums(counts(sce)) > 0)
R> system.time(res <- glmpca(counts(sce)[nonzero,], L=10, penalty=100))
# time passes...
Error in glmpca(counts(sce)[nonzero, ], L = 10, penalty = 100) :
  Numerical divergence (deviance no longer finite), try increasing the penalty to improve stability of optimization.
Timing stopped at: 7452 2672 1.012e+04
```

I keep hoping to use glmpca for geometric sketching at some point, but if it blows up every time I run it, that will probably not happen any time soon.  FWIW, BiocSingular *also* blows up, so maybe I'm just breaking the underlying libraries.  Still -- 40K isn't really that many cells.

**Comment by willtownes** [comment]
original twitter thread for reference: https://twitter.com/timtriche/status/1187030824081903618

**Comment by willtownes** [comment]
@ttriche can you try subsetting the genes down to say 2K or 5K genes? Either just take a random sample of genes or (preferably) using deviance or just picking the mostly highly expressed genes.

**Comment by GAgafencu** [comment]
Dear Will,

I am encountering a similar problem to the one encountered by @ttriche, even though my data set is substantially smaller (13718 cell x 18556 genes). It would be handy to know which was the indication that you offered @ttriche in the original twitter thread (https://twitter.com/timtriche/status/1187030824081903618) as that thread is no longer available.

Thank you for your help. Grigore-Aristide Gafencu

**Comment by willtownes** [comment]
Hi @GAgafencu , Sorry I can't remember exactly what we discussed on the twitter thread, but in general I would suggest trying to subset the genes down to say 2,000 based on [deviance](https://github.com/willtownes/scrna2019/blob/master/util/functions_genefilter.R#L6) before running glm-pca. Also, sometimes it is more numerically stable with negative binomial likelihood instead of Poisson. Also it would help to know how many dimensions you are asking it to fit? Fewer dimensions usually is more numerically stable.

**Comment by GAgafencu** [comment]
Thanks a lot for the quick and informative reply. I am currently asking 20 dimensions as I am trying to see how it measures up with traditional PCA in the conventional Seurat workflow. Currently, I fixed the issue by running the glmpca function with a penalty = 100 and it seems to work fine, but the command has not finished running yet and if it crashes again I'll try to subset my gene list based on deviance.
Thank you again for your suggestions and for developing this tool as it might be the right one to sift through noisy and sparse 10X datasets.

**Comment by kaizen89** [comment]
I have the same problem with 1000 genes,10 PCs and 10K cells.

**Comment by willtownes** [comment]
version 0.2.0 (now installable from github) should address these concerns.
